---
env:
  global:
  - secure: |-
      Ykan1oCC5YTcgamvRI9QS7ZlmBx/OnwG4GDBPcmY6D0IK67pci4Mmwa0DP/p
      g1WzA8eaKjiJgwZ0IHjSpayTH0OPtMOeaqcnSP6iDD2vll1D2FSMsZgzF2eU
      +bkyXnCdORz8Ax+JQEztCl+NFUw/5u6WbhqwkPv90PSy9xfsWCY=
  - secure: |-
      nDe0EMyj1EBTpYb32UxiXtpkSEBX2g7d5WD81Jz8EouFbqi5oop5jcjynjqh
      BaO+ECxoJV8BvWTbiCttXKfcXGQSLuUqNluK6+2aWzrhX5iWWxbS1aVs9jXf
      BAq2mfW+P+/ifcHuNbYiLu2hWfzd/QfEYlArsAtHu0eUBEbpRx0=
  - secure: |-
      dHpiaMiPjrdoVrolQICOUkaJ0womQ2OVsoIMAAeEFSVDgWICBrQ3b/SUZKBS
      qKR5444v25pnXHjxLD5JrWL2aiBOYLr4VpWI8ejpl4JZtb7Tia5yB2OBC3FP
      H1EF1eUnEJ/7jJvsWOMtPXloiJxE8EJTNUhoES0qwSCwUSNAMl0=
language: node_js
node_js:
- "0.10"
- "0.8"
before_install:
- sudo apt-get install subversion
- curl -o http://www.imagemagick.org/download/ImageMagick-6.8.6-4.tar.gz
- tar xvzf ImageMagick-6.8.6-4.tar.gz
- cd ImageMagick-6.8.6-4
- ./configure
- make
- sudo make install