---
env:
  global:
  - secure: |-
      Ykan1oCC5YTcgamvRI9QS7ZlmBx/OnwG4GDBPcmY6D0IK67pci4Mmwa0DP/p
      g1WzA8eaKjiJgwZ0IHjSpayTH0OPtMOeaqcnSP6iDD2vll1D2FSMsZgzF2eU
      +bkyXnCdORz8Ax+JQEztCl+NFUw/5u6WbhqwkPv90PSy9xfsWCY=
  - secure: |-
      nDe0EMyj1EBTpYb32UxiXtpkSEBX2g7d5WD81Jz8EouFbqi5oop5jcjynjqh
      BaO+ECxoJV8BvWTbiCttXKfcXGQSLuUqNluK6+2aWzrhX5iWWxbS1aVs9jXf
      BAq2mfW+P+/ifcHuNbYiLu2hWfzd/QfEYlArsAtHu0eUBEbpRx0=
  - secure: |-
      dHpiaMiPjrdoVrolQICOUkaJ0womQ2OVsoIMAAeEFSVDgWICBrQ3b/SUZKBS
      qKR5444v25pnXHjxLD5JrWL2aiBOYLr4VpWI8ejpl4JZtb7Tia5yB2OBC3FP
      H1EF1eUnEJ/7jJvsWOMtPXloiJxE8EJTNUhoES0qwSCwUSNAMl0=
language: node_js
node_js:
- "0.10"
before_install:
- sudo apt-get update
- sudo apt-get install imagemagick ffmpeg libjpeg-dev libpng-dev libtiff-dev
- sudo apt-get upgrade
- curl -O https://webp.googlecode.com/files/libwebp-0.3.1.tar.gz
- tar xvzf libwebp-0.3.1.tar.gz
- cd libwebp-0.3.1
- ./configure
- make
- sudo make install
- cd ..
- curl -O http://www.imagemagick.org/download/ImageMagick-6.8.6-8.tar.gz
- tar xvfz ImageMagick-6.8.6-8.tar.gz
- cd ImageMagick-6.8.6-8
- ./configure --with-webp=yes
- make
- sudo make install
- sudo ldconfig /usr/local/lib
- cd ..