---
node_js:
- "0.10"
language: node_js
env:
  global:
  - secure: |-
      EXUZSW3K1MtBnCoFADIIP1mWhpy2FbkLVotAHs0QEkS6vbfSVSbVVpCr5M7R
      9GUluxU5/q9sjycBilcMWTmp6I0fibMXVRoNhF6Fptew1+2HpdyTdLJpV6DY
      wsCCfY/Db1s1a7u687XKHiLz20CWGLR4o1JwKU5++bosmJi4aYw=
  - secure: |-
      J7DQTbVgMlatjZnsNOLS0r9XwobAMhGTIzx9XsDRdwE6xaV2ADS0utUtSkFF
      BTCQJ1Wi4Is6dgauS/MlmK1wHo+wqkOi6+16cpecUZZ8vwYKW6hv52h8/73t
      vvwHnPaWM0aQL01+v6lm67/80QXqq0bxEv9mbiHblBeCdskbdOA=
  - secure: |-
      gCMdIyDN9us+uu8sClqj9qq9HcDlkMUzIad6AQ66xi7uswBujijPZj7b0dfb
      4EbJ8QFFgxfXlC4i2TtYvWlJdttYtlG7lp7f2b//nuGj4TvbeX/CDMoiXWtI
      p/aB33zcPS/RqKwQCfMZ9dVXSSrCfRmz87g/6B1VBEDCsQNhdXU=
  - secure: |-
      ieiOSRsJdcdBt58wyIwn7XY/of1WIyZo/qbQJLuY+AOPEIEFbSkk/IHvK610
      dFHaRkYBmYl0+NsssmiAf0edDGBgrU4jqchv7XttyYIGcyzXMnnFHFX8zFJ4
      DNZ0MgI30XYVyRyy3Euc+5pEO5rJsNMU0ZqHezD0jHqroLAhyeE=
  - secure: |-
      WGpghTkUNXIthPopbl6QsrRK7d9WrdPqJQb5SzKA/Lmf8smOcaLg/uPnNkCr
      TRNA0s7jdWcQX0UkMATClUawiD8dyAaTo/zrUg7c+4kBqibEV34UJwIT7awJ
      ev9oXBQOe+6KWVPMdSORts8PH6Cb0+wMk+iV2TNFYNfKh7mnOOA=
  - secure: |-
      VHWs5Lkedl4Mnb85yKVizuq7k9jSlhDHOgSX7jNh9TIcibP0KZPh1UO5ORCv
      3H50W1TWfHd0lNp849zwyu7//1lKwTjlW8J/T20nU98UgwBvo4aykss0TVTj
      BHOqWWLRy1MlqNFb0JOh8BZdSChNLbmfIn2f61ljYZ0rWqu7njU=
before_install:
- sudo apt-get update
- sudo apt-get install imagemagick ffmpeg libjpeg-dev libpng-dev libtiff-dev
- sudo apt-get upgrade
- curl -O https://webp.googlecode.com/files/libwebp-0.3.1.tar.gz
- tar xvzf libwebp-0.3.1.tar.gz
- cd libwebp-0.3.1
- ./configure
- make
- sudo make install
- cd ..
- curl -O http://www.imagemagick.org/download/ImageMagick-6.8.6-9.tar.gz
- tar xvfz ImageMagick-6.8.6-9.tar.gz
- cd ImageMagick-6.8.6-9
- ./configure --with-webp=yes
- make
- sudo make install
- sudo ldconfig /usr/local/lib
- cd ..
